# https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions

name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run lint
      run: npm run lint
    - name: Run test
      run: npm run test
